Story5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homePage.urls')),
    path('schedule/', include('schedule.urls')),
]

homePage/urls.py
from django.urls import path
from . import views

app_name = 'homePage'

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('mainPage/', views.mainPage, name='mainPage'),
    path('formPage/', views.formPage, name='formPage'),
]

schedule/urls.py
from django.urls import path
from .views import schedule, addSchedule, clearSchedule

urlpatterns = [
    path('', schedule, name='schedule'),
    path('add/', addSchedule, name='addSchedule'),
    path('clear/', clearSchedule, name='clearSchedule'),
]

homePage/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    day = models.CharField(max_length=30)
    date = models.DateField(max_length=30, null=True)
    time = models.TimeField(max_length=30, null=True)
    name = models.CharField(max_length=30)
    place = models.CharField(max_length=30)
    categories = models.CharField(max_length=30)

schedule/forms.py
from django import forms

class AddSchedule(forms.ModelForm):
    name = forms.CharField(label='Nama Kegiatan', required=True, max_length=30, widget=forms.TextInput())
    day = forms.CharField(label='Hari', required=True, max_length=30, widget=forms.TextInput())
    date = forms.DateField(label="Tanggal", widget=forms.DateInput(attrs={'type':'date', 'class':'col-12', 'style':'margin-bottom:3vw'}))
    time = forms.TimeField(label='Waktu', required=True, widget=forms.TimeInput(attrs={'type': 'time', 'class':'col-12', 'style':'margin-bottom:3vw'}))
    place = forms.CharField(label='Tempat Kegiatan', required=True, max_length=30, widget=forms.TextInput())
    categories = forms.CharField(label='Kategori', required=True, max_length=30, widget=forms.TextInput())

homePage/views.py
from django.shortcuts import render

# Create your views here.
def homePage(request):
    return render(request, 'homePage.html')

def mainPage(request):
    return render(request, 'mainPage.html')

def formPage(request):
    return render(request, 'formPage.html')
    

schedule/views.py
from django.shortcuts import render, redirect
from .forms import AddSchedule
from .models import Schedule

app_name = 'homepage'

# Create your views here.
response = {}
def schedule(request):
    response['jadwal'] = Schedule.objects.all().values()
    return render(request, 'schedule.html', response)

def addSchedule(request):
    form = AddSchedule(request.POST)
    if(request.method == 'POST' and form.is_valid()):
        model = Schedule(
            day = request.POST['day'],
            date = request.POST['date'],
            time = request.POST['time'],
            name = request.POST['name'],
            place = request.POST['place'],
            categories = request.POST['categories']
        )
        model.save()
    return redirect("addSchedule")

def clearSchedule(request):
    response = {}
    response['jadwal'] = Schedule.objects.all().delete()
    return redirect('schedule')

homePage/templates/homePage.html
<!doctype html>
{% load static %}
<html lang="en">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"></link>
  <link rel="stylesheet" href="{% static 'css/style.css' %}"></link>
  <link href="https://fonts.googleapis.com/css?family=Kodchasan&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Robotoi&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

  <body background="{% static 'images/BackgroundHome.png' %}">
    <div class="midBox">
      <img src="{% static 'images/ProfilePicture.png' %}" class="profImg">
      <div>
        <p class="name">Hi, I'm Hanrichie</p>
        <p class="npm">NPM : 1806141214</p>
        <p class="desc">I am a student at Universitas Indonesia studying Computer Science, interested in web and application development.</p>
        <a href="{% url 'homePage:mainPage' %}"><button type="button" class="btn btn-outline-dark">Learn More</button></a>
      </div>
    </div>

  </body>
</html>

homePage/templates/mainPage.html
<!doctype html>
{% load static %}
<html lang="en">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" a href="{% static 'css/bootstrap.css' %}"></link>
  <link rel="stylesheet" a href="{% static 'css/style.css' %}"></link>
  
  <link href="https://fonts.googleapis.com/css?family=Kodchasan&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

  <body background="{% static 'images/BackgroundMain.png' %}">
    <div class="topnav" id="top">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="nav-link" href="#smoothEdu"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navToogle">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navToogle">
                <ul class="navbar-nav ml-auto">
                    <li class="navText nav-item active">
                        <a class="nav-link" href="{% url 'homePage:homePage' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="navText nav-item active">
                        <a class="nav-link" href="#smoothEdu">Education <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="navText nav-item active">
                        <a class="nav-link" href="#smoothSkill">Skills <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="navText nav-item active">
                        <a class="nav-link" href="#smoothActv">Activities <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="navText nav-item active">
                        <a class="nav-link" href="{% url 'schedule' %}">Schedule <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="navText nav-item active">
                        <a class="nav-link" href="#smoothContact">Contact <span class="sr-only">(current)</span></a>
                    </li>
                    <a href="{% static 'js/functions.js' %}" class="icon" onclick="toogleNav()">
                        <i class="fa fa-bars"></i>
                    </a>
                </ul>
            </div>
        </nav>
    </div>
    <div>
        <p class="aboutMe">About Hanrichie</p>
        <p class="aboutDesc">Hanrichie was born at Tangerang Selatan on 15 May 2002, which makes 
            him 2 years younger than normal students. He loves doing any kind of sport, but the 
            one sport he loves doing most is table tennis.</p>
    </div>
    <div class="position-fixed">
        <a href="#top"><img src="{% static 'images/ArrowUp.png' %}" class="arrowUp"></a>
    </div>
    <div id="smoothEdu">
        <p class="headerText">Education</p>
        <div class="flexEdu">
            <div class="edu">
                <p>Universitas Indonesia</p>
                <p>SMAN 2 Tangerang Selatan</p>
                <p>SMP Ehipassiko BSD</p>
            </div>
            <div class="line"></div>
            <div class="year">
                <p>2018 - current</p>
                <p>2016 - 2018</p>
                <p>2013 - 2016</p>
            </div>
        </div>
    </div>
    <div id="smoothSkill">
        <p class="headerText">Skills</p>
        <div class="skillLogo">
            <img src="{% static 'images/PythonLogo.png' %}" class="pythonLogo roundSquareTag">
            <img src="{% static 'images/JavaLogo.png' %}" class="javaLogo roundSquareTag">
            <img src="{% static 'images/HTMLLogo.png' %}" class="htmlLogo roundSquareTag">
            <img src="{% static 'images/CSSLogo.png' %}" class="cssLogo roundSquareTag">
            <img src="{% static 'images/JSLogo.png' %}" class="jsLogo roundSquareTag">
        </div>
    </div>
    <div id="smoothActv">
        <p class="headerText">Activities</p>
        <div class="actvBox">
            <div class="actv">
                <p class="actvText">Staff of Adkesma</p>
                <p class="actvText">BEM Fasilkom UI 2018</p>
            </div>
            <div class="actv">
                    <p class="actvText">Head of Event</p>
                    <p class="actvText">Wisuda Genap Fasilkom 2018</p>
            </div>
        </div>
        <div class="actvBox">
            <div class="actv">
                <p class="actvText">Staff of Adkesma</p>
                <p class="actvText">BEM Fasilkom UI 2018</p>
            </div>
            <div class="actv">
                <p class="actvText">Staff of Adkesma</p>
                <p class="actvText">BEM Fasilkom UI 2018</p>
            </div>
        </div>
    </div>
    <div id="smoothContact">
        <p class="headerText">Contact</p>
        <div class="contactText">
            <p>Email        : hanrichie55@gmail.com</p>
            <p>Line         : hanrichie</p>
            <p>Whatsapp     : +6287896933360</p>
        </div>
        <div class="reachMeOn">
            <p>Also reach me on..</p>
        </div>
        <div class="contactImage">
            <div class="contactLogo">
                <a href="https://www.linkedin.com/in/hanrichie-hong-80120317a/">
                    <img src="{% static 'images/LinkedIn.png' %}" class="contactLogo"></a>
            </div>
            <div class="contactLogo">
                <a href="https://www.instagram.com/hanrichie_/"><img src="{% static 'images/Instagram.png' %}" class="contactLogo"></a>
            </div>
            <div class="contactLogo">
                <a href="https://twitter.com/am_hsquare"><img src="{% static 'images/Twitter.png' %}" class="contactLogo"></a>
            </div>
        </div>
    </div>
    
    <script src="{% static 'js/functions.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
   
  </body>
</html>

schedule/templates/addSchedule.html
<!doctype html>
{% load static %}
<html lang="en">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" a href="{% static 'css/bootstrap.css' %}"></link>
  <link rel="stylesheet" a href="{% static 'css/style2.css' %}"></link>

  <link href="https://fonts.googleapis.com/css?family=Kodchasan&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons">
  <link href="dist/css/propeller.min.css">
  <link href="datetimepicker/css/bootstrap-datetimepicker.css">
  <link href="datetimepicker/css/pmd-datetimepicker.css">

  <body>
        <a href="/schedule/schedule">
            <button class ="btn" type="submit" style="margin-bottom: 2vw; margin-left: 75vw; margin-top: 2vw">Check Schedules</button>
        </a>
        <form action="/schedule/addSchedule" method="POST">
        <div style="background-color: white" class="container">
            <h1>Schedules</h1>
            <p>Please fill in this form to add a schedules</p>
            <hr>
            {% csrf_token %}
            {{ form }}

            <button style="margin-bottom: 3vw" type="submit" value="Submit" class="registerbtn">Submit</button>
        </div>
        </form>

        <script src="{% static 'js/functions2.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    </body>
</html>            

schedule/templates/schedule.html
<!doctype html>
{% load static %}
<html lang="en">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" a href="{% static 'css/bootstrap.css' %}"></link>
  <link rel="stylesheet" a href="{% static 'css/style2.css' %}"></link>

  <link href="https://fonts.googleapis.com/css?family=Kodchasan&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons">

  <body>
    <div class="topnav" id="top">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="nav-link" href="#smoothEdu"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navToogle">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navToogle">
                <ul class="navbar-nav ml-auto">
                    <li class="navText nav-item active">
                        <a class="nav-link" href="{% url 'homePage:homePage' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="navText nav-item active">
                        <a class="nav-link" href="{% url 'homePage:mainPage' %}">Profile <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="navText nav-item active">
                        <a class="nav-link" href="{% url 'schedule' %}">Schedule <span class="sr-only">(current)</span></a>
                    </li>
                    <a href="{% static 'js/functions2.js' %}" class="icon" onclick="toogleNav()">
                        <i class="fa fa-bars"></i>
                    </a>
                </ul>
            </div>
        </nav>
    </div>
    <div class="container">
        <p class="headerText">Add Schedule</p>
        <div>
            <label for="ex3">Nama Kegiatan :</label>
            <input class="form-control inputSize" id="ex3" type="text">
        </div>
        <div>
            <label for="ex3">Hari :</label>
            <input class="form-control inputSize" id="ex3" type="text">
        </div>
        <div>
            <label for="ex3">Tanggal Kegiatan :</label>
            <input class="form-control inputSize" id="ex3" type="text">
        </div>
        <div>
            <label for="ex3">Waktu Kegiatan :</label>
            <input class="form-control inputSize" id="ex3" type="text">
        </div>
        <div>
            <label for="ex3">Tempat Kegiatan :</label>
            <input class="form-control inputSize" id="ex3" type="text">
        </div>
        <div>
            <label for="ex3">Kategori Kegiatan :</label>
            <input class="form-control inputSize" id="ex3" type="text">
        </div>
        <a href="{% url 'addSchedule' %}"><button type="button" class="btn btn-primary">Add Schedule</button></a>
    </div>
    <div>
		<a href="{% url 'clearSchedule' %}" >
			<button class ="btn" type="submit" style="margin-bottom: 3vw">Delete Schedules</button>
		</a>
		{% for result in response %}
		<div class="kotak">
			<article id="course-name">Nama Kegiatan : {{result.name}}</article>
			<article id="course-name">Hari : {{result.day}}</article>
			<article id="course-name">Tanggal Kegiatan : {{result.date}}</article>
			<article id="course-name">Waktu Kegiatan : {{result.time}}</article>
			<article id="course-name">Tempat Kegiatan : {{result.place}}</article>
			<article id="course-name">Kategori Kegiatan : {{result.categories}}</article>
			<p> </p>
		</div>
		{% endfor %}
	</div>

      <script src="{% static 'js/functions2.js' %}"></script>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  </body>
</html>